name: Build Prime Kernel (y2q)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [y2q]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip \
            zstd \
            python3

      - name: Clone ThankYouMario Clang prebuilts
        run: |
          git clone --depth=1 -b 18 https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone clang-tc

      - name: Build kernel
        run: |
          chmod +x build_prime.sh
          bash build_prime.sh "${{ matrix.device }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PrimeKernel-${{ matrix.device }}
          path: "*.zip"
